engines/admin/config/routes.rb
Admin::Engine.routes.draw do
  root 'dashboards#index'

  resources :accounts, except: %i[show new create] do
    member do
      put :accept
      put :decline
    end
  end
  resources :cities, except: :show
  resources :regions, except: :show
  resources :countries, except: :show
  resources :pages, except: :show do
    post :sort, on: :collection
  end
  resources :articles, except: :show
  resources :messages, only: %i[index show]
  resources :volunteers, only: :index
  resources :subscribers, only: :index
  resources :newsletters, except: :show
  resources :sidebar_contents, except: :show, path: :sidebar
  resource :slider, only: %i[edit update]
  resource :social_network, only: %i[edit update]
  resource :configuration, only: %i[edit update]
  resource :language, only: %i[edit update]
  resource :about, only: %i[edit update], controller: :about
  resource :user, only: %i[edit update]
  resource :domain, only: %i[edit update]

  get '/:resource/:resource_id/translations' => 'translations#index', as: :translations

  namespace :api do
    resources :regions, only: :index
    resources :cities, only: :index
  end

  match '*path' => 'errors#not_found', via: :all
end

engines/admin/app/controllers/admin/accounts_controller.rb
require_dependency 'admin/application_controller'

module Admin
  class AccountsController < ApplicationController
    before_action :set_account, except: :index

    def index
      authorize Content::Account

      @accounts =
        policy_scope(Content::Account)
          .includes(:owner, address: :country)
          .order('content_accounts.created_at DESC')
    end

    def update
      if @account.update(account_params)
        redirect_to edit_account_url(@account), notice: 'Account was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @account.destroy
      redirect_to accounts_url, notice: 'Account was successfully destroyed.'
    end

    def accept
      @account.update_column(:status, :accepted)
      Content::AccountMailer.accept_entry(@account, generate_raw_for_edit_password_url).deliver_later
      redirect_to accounts_url, notice: 'Account was successfully accepted.'
    end

    def decline
      @account.update_column(:status, :declined)
      Content::AccountMailer.decline_entry(@account).deliver_later
      redirect_to accounts_url, notice: 'Account was successfully declined.'
    end

    private

    def set_account
      @account = authorize Content::Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(policy(%i[content account]).permitted_attributes)
    end

    def generate_raw_for_edit_password_url
      user = @account.owner

      raw, enc = Devise.token_generator.generate(user.class, :reset_password_token)

      user.reset_password_token = enc
      user.reset_password_sent_at = Time.current
      user.save(validate: false)

      raw
    end

    def wrapper_center?
      action_name != 'index'
    end
    helper_method :wrapper_center?
  end
end

engines/admin/app/helpers/admin/accounts_helper.rb
module Admin
  module AccountsHelper
    def account_class_name_status(status)
      if status == 'pending'
        'active'
      elsif status == 'accepted'
        'success'
      elsif status == 'declined'
        'danger'
      end
    end
  end
end

engines/admin/app/views/admin/accounts/_form.html.erb
<%= simple_form_for account, wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>

  <%= f.simple_fields_for :owner do |owner| %>
    <%= form_group_for owner, :authentication_token do %>
      <%= owner.input :generate_authentication_token, label: false %>

      <div class='authentication_token_path'>
        <%= root_url(authentication_token: owner.object.authentication_token) if owner.object.authentication_token.present? %>
      </div>
    <% end %>
  <% end %>

  <hr>

  <%= f.input :subdomain %>
  <%= f.input :responsable %>
  <%= f.simple_fields_for :owner do |owner| %>
    <%= owner.input :email, input_html: { autocomplete: 'email' } %>
  <% end %>

  <hr>

  <%= f.simple_fields_for :address do |address| %>
    <%= address.input :phone %>
    <%= address.input :address1 %>
    <%= address.input :zip_code %>
    <%= address.input :city_name %>
    <%= address.input :region_name %>
    <%= address.input :country_id, collection: Content::Country.all %>
    <%= address.input :longitude %>
    <%= address.input :latitude %>
  <% end %>

  <%= f.button :submit, class: 'btn btn-info pull-right' %>
<% end %>

engines/admin/app/views/admin/accounts/edit.html.erb
<% content_for :page_title do %>
  <%= t('.header') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to t('shared.actions.back_to_list'), accounts_path, class: 'btn btn-secondary' %>
<% end %>

<%= render 'form', account: @account %>

engines/admin/app/views/admin/accounts/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Content::Account) %>
<% end %>

<p><%= t('admin.shared.total', count: @accounts.count) %></p>

<div class='table-responsive'>
  <table class='table table-striped table-sm'>
    <thead>
      <tr>
        <th>#</th>
        <th><%= Content::Account.human_attribute_name(:mosque) %></th>
        <th><%= Content::Account.human_attribute_name(:subdomain) %></th>
        <th><%= Content::User.human_attribute_name(:email) %></th>
        <th><%= Content::Account.human_attribute_name(:responsable) %></th>
        <th><%= Content::User.human_attribute_name(:confirmed_at) %></th>
        <th><%= Content::Address.model_name.human %></th>
        <th colspan='3'></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr class="table-<%= account_class_name_status(account.status) %>">
          <td><%= account.id %></td>
          <td><%= account.mosque %></td>
          <td><%= account.subdomain %></td>
          <td>
            <%= account.owner.email %>
            <% if account.owner.unconfirmed_email? %>
              <br />
              <span class='badge badge-warning'>
                <%= account.owner.unconfirmed_email %>
              </span>
            <% end %>
          </td>
          <td><%= account.responsable %></td>
          <td><%= account.owner.confirmed_at&.to_formatted_s(:long) %></td>
          <td><%= account.address.to_s %></td>
          <td><%= link_to t('shared.actions.edit'), edit_account_path(account), class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to t('shared.actions.accept'), accept_account_path(account), method: :put, data: { confirm: t('admin.shared.are_you_sure') }, class: 'btn btn-success btn-sm' if account.pending? %></td>
          <td><%= link_to t('shared.actions.decline'), decline_account_path(account), method: :put, data: { confirm: t('admin.shared.are_you_sure') }, class: 'btn btn-danger btn-sm' if account.pending? %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>