engines/admin/config/routes.rb
Admin::Engine.routes.draw do
  root 'dashboards#index'

  resources :accounts, except: %i[show new create] do
    member do
      put :accept
      put :decline
    end
  end
  resources :cities, except: :show
  resources :regions, except: :show
  resources :countries, except: :show
  resources :pages, except: :show do
    post :sort, on: :collection
  end
  resources :articles, except: :show
  resources :messages, only: %i[index show]
  resources :volunteers, only: :index
  resources :subscribers, only: :index
  resources :newsletters, except: :show
  resources :sidebar_contents, except: :show, path: :sidebar
  resource :slider, only: %i[edit update]
  resource :social_network, only: %i[edit update]
  resource :configuration, only: %i[edit update]
  resource :language, only: %i[edit update]
  resource :about, only: %i[edit update], controller: :about
  resource :user, only: %i[edit update]
  resource :domain, only: %i[edit update]

  get '/:resource/:resource_id/translations' => 'translations#index', as: :translations

  namespace :api do
    resources :regions, only: :index
    resources :cities, only: :index
  end

  match '*path' => 'errors#not_found', via: :all
end

engines/admin/app/controllers/admin/api/regions_controller.rb
module Admin
  module Api
    class RegionsController < ActionController::Base
      def index
        @regions =
          if params[:country_id]
            Content::Region.where(country_id: params[:country_id])
          else
            Content::Region.all
          end

        render json: { regions: @regions.map { |region| { id: region.id, name: region.name } } }
      end
    end
  end
end

engines/admin/app/controllers/admin/regions_controller.rb
require_dependency 'admin/application_controller'

module Admin
  class RegionsController < ApplicationController
    before_action :set_region, only: %i[edit update destroy]

    def index
      authorize Content::Region

      @countries = policy_scope(Content::Country)

      @regions = policy_scope(Content::Region).where(
        {}.tap do |conditions|
          if params[:country_id]
            conditions[:country_id] = params[:country_id]
          else
            conditions[:country] = @countries.first
          end
        end
      )
    end

    def new
      @region = authorize Content::Region.new
    end

    def create
      @region = authorize Content::Region.new(region_params)

      if @region.save
        redirect_to regions_url, notice: 'Region was successfully created.'
      else
        render :new
      end
    end

    def update
      if @region.update(region_params)
        redirect_to regions_url, notice: 'Region was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @region.destroy
      redirect_to regions_url, notice: 'Region was successfully destroyed.'
    end

    private

    def set_region
      @region = authorize Content::Region.find(params[:id])
    end

    def region_params
      params.require(:region).permit(:name, :country_id)
    end
  end
end

engines/admin/app/views/admin/regions/_form.html.erb
<%= simple_form_for region do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :country_id, collection: Content::Country.all, label_method: :name, value_method: :id %>

  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

engines/admin/app/views/admin/regions/edit.html.erb
<% content_for :page_title do %>
  <%= t('.header') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to t('shared.actions.back_to_list'), regions_path, class: 'btn btn-secondary' %>
<% end %>

<%= render 'form', region: @region %>

engines/admin/app/views/admin/regions/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Content::Region) %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to t('shared.actions.new'), new_region_path, class: 'btn btn-info' %>
<% end %>

<%= form_tag regions_path, method: :get do %>
  <div class='form-row'>
    <div class='form-group col-md-3'>
      <%= select_tag :country_id, options_for_select(@countries.map { |c| [c.name, c.id] }, params[:country_id]), class: 'form-control' %>
    </div>
    <div class='form-group col-md-3'>
      <%= submit_tag 'Search', class: 'btn btn-secondary btn-sm' %>
    </div>
  </div>
<% end %>

<p><%= t('admin.shared.total', count: @regions.size) %></p>

<div class='table-responsive'>
  <table class='table table-striped table-sm'>
    <thead>
      <tr>
        <th>#</th>
        <th><%= Content::Region.human_attribute_name(:name) %></th>
        <th><%= Content::Country.model_name.human %></th>
        <th colspan='2'></th>
      </tr>
    </thead>

    <tbody>
      <% @regions.each do |region| %>
        <tr>
          <td><%= region.id %></td>
          <td><%= region.name %></td>
          <td><%= region.country.name %></td>
          <td><%= link_to t('shared.actions.edit'), edit_region_path(region), class: 'btn btn-success btn-sm' %></td>
          <td><%= link_to t('shared.actions.delete'), region, method: :delete, data: { confirm: t('admin.shared.are_you_sure') }, class: 'btn btn-danger btn-sm' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

engines/admin/app/views/admin/regions/new.html.erb
<% content_for :page_title do %>
  <%= t('.header') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to t('shared.actions.back_to_list'), regions_path, class: 'btn btn-secondary' %>
<% end %>

<%= render 'form', region: @region %>