engines/landing/config/routes.rb
Landing::Engine.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'home#index'

    get '/accounts/success-page', to: 'accounts#success_page', as: :success_page
    resources :accounts, only: %i[new create]
    resources :volunteers, only: %i[new create]

    devise_for(:users, {
      class_name: 'Content::User',
      controllers: {
        sessions: 'landing/user_sessions',
        passwords: 'landing/user_passwords',
        confirmations: 'landing/user_confirmations'
      },
      router_name: :landing
    })

    devise_scope :user do
      get '/login', to: 'user_sessions#new', as: :login
      post '/login', to: 'user_sessions#create', as: :create_new_session
      match '/logout', to: 'user_sessions#destroy', as: :logout, via: :delete
      get '/password/recover', to: 'user_passwords#new', as: :recover_password
      post '/password/recover', to: 'user_passwords#create', as: :reset_password
      get '/password/change', to: 'user_passwords#edit', as: :edit_password
      put '/password/change', to: 'user_passwords#update', as: :update_password
      get '/confirm', to: 'user_confirmations#new', as: :confirmation
      post '/confirm', to: 'user_confirmations#create', as: :resend_confirmation
    end

    get '/422', to: 'errors#unacceptable'
    get '/500', to: 'errors#internal_error'
    match '*path' => 'errors#not_found', via: :all
  end
end

engines/landing/app/controllers/landing/accounts_controller.rb
require_dependency 'landing/application_controller'

module Landing
  class AccountsController < ApplicationController
    def new
      @account = Content::Account.new
      @account.build_address
      @account.build_owner
    end

    def create
      @account = accounts_service.create

      if @account.persisted?
        redirect_to success_page_path
      else
        render :new
      end
    rescue StandardError
      redirect_to new_account_path, alert: t('landing.accounts.create.error_message')
    end

    private

    def account_params
      params.require(:account).permit(policy(%i[content account]).permitted_attributes)
    end

    def accounts_service
      Landing::AccountsService.new(account_params)
    end
  end
end

engines/landing/app/controllers/landing/application_controller.rb
module Landing
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    include Pundit
    include Content::AccountsHelper
    include Content::GoogleTagManagerHelper
    include Content::LayoutHelper
    include Landing::ControllerHelpers::Locale
    include Landing::ControllerHelpers::SeoContent

    private

    def after_sign_in_path_for(resource)
      stored_location_for(resource) || '/admin'
    end
  end
end

engines/landing/app/controllers/landing/errors_controller.rb
require_dependency 'landing/application_controller'

module Landing
  class ErrorsController < ApplicationController
    include Content::SharedErrors
  end
end

engines/landing/app/controllers/landing/home_controller.rb
require_dependency 'landing/application_controller'

module Landing
  class HomeController < ApplicationController
    include Content::AccountsHelper

    layout 'landing/landing'

    def index
      @accounts = Content::Account.accepted.includes(address: :country)
    end
  end
end

engines/landing/app/controllers/landing/user_confirmations_controller.rb
module Landing
  class UserConfirmationsController < Devise::ConfirmationsController
  end
end

engines/landing/app/controllers/landing/user_passwords_controller.rb
module Landing
  class UserPasswordsController < Devise::PasswordsController
  end
end

engines/landing/app/controllers/landing/user_sessions_controller.rb
module Landing
  class UserSessionsController < Devise::SessionsController
  end
end

engines/landing/app/controllers/landing/volunteers_controller.rb
require_dependency 'landing/application_controller'

module Landing
  class VolunteersController < ApplicationController
    helper Content::ControllerHelpers::Volunteer

    layout 'landing/landing'

    def new
      @volunteer = Content::Volunteer.new
    end

    def create
      @volunteer = Content::Volunteer.new(volunteer_params)

      if @volunteer.save
        redirect_to new_volunteer_url, notice: 'Volunteer was successfully created.'
      else
        render :new
      end
    end

    private

    def volunteer_params
      params.require(:volunteer).permit(policy([:content, :volunteer]).permitted_attributes)
    end
  end
end

engines/landing/app/helpers/landing/application_helper.rb
module Landing
  module ApplicationHelper
    LOCALE_ICON_MAPPING = {
      'ar' => 'sa',
      'ca' => 'es-ct',
      'en' => 'us',
      'fa' => 'ir',
      'ur' => 'pk'
    }.freeze

    def locale_with_icon(locale)
      icon_suffix = LOCALE_ICON_MAPPING[locale.to_s] || locale

      icon = content_tag(
        :span,
        nil,
        class: "flag-icon flag-icon-#{icon_suffix}"
      )

      [icon, t("shared.locales.#{locale}")].join(' ').html_safe
    end

    def alternate_locales
      I18n.available_locales.reject { |locale| locale == I18n.locale.to_sym }
    end
  end
end

engines/landing/app/views/landing/accounts/_form.html.erb
<%= simple_form_for @account do |f| %>
  <%= f.error_notification %>

  <%= f.input :subdomain, wrapper: :input_group, prepend: protocol, append: ".#{Rails.application.credentials.project_name}" %>

  <%= f.simple_fields_for :owner do |owner| %>
    <%= owner.input :email, input_html: { autocomplete: 'email' } %>
  <% end %>

  <%= f.input :responsable %>

  <%= f.input :mosque %>

  <%= f.simple_fields_for :address do |address| %>
    <%= address.input :phone %>

    <div class='row'>
      <div class='col-sm-9'>
        <%= address.input :address1 %>
      </div>

      <div class='col-sm-3'>
        <%= address.input :zip_code %>
      </div>
    </div>

    <div class='row'>
      <div class='col-sm-4'>
        <%= address.input :city_name %>
      </div>

      <div class='col-sm-4'>
        <%= address.input :region_name %>
      </div>

      <div class='col-sm-4'>
        <%= address.input :country_id, collection: Content::Country.all, label_method: :name, value_method: :id %>
      </div>
    </div>
  <% end %>

  <%= f.button :submit, class: 'btn btn-block' %>
<% end %>

engines/landing/app/views/landing/accounts/new.html.erb
<h1 class='form-header'>
  <%= t('landing.accounts.new.header') %>
</h1>

<div class='row devise'>
  <div class='col-md-6 image'>
    <%= image_tag 'landing/accounts.png', alt: t('landing.accounts.new.header'), class: 'img-fluid' %>
  </div>

  <div class='col-md-6'>
    <%= render 'form' %>
  </div>
</div>

engines/landing/app/views/landing/accounts/success_page.html.erb
<div class='col-md-8 offset-md-2'>
  <div class='alert alert-success' role='alert'>
    <h4 class='alert-heading'>
      <%= t('landing.accounts.success_page.header') %>
    </h4>
    <hr>
    <p>
      <%= t('landing.accounts.success_page.body_html') %>
    </p>
  </div>
</div>

engines/landing/app/views/landing/shared/_devise_error_messages.html.erb
<% if resource.errors.any? %>
  <div class='alert alert-danger'>
    <h2>
      <%= t('simple_form.error_notification.default_message') %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

engines/landing/app/views/landing/shared/_devise_links.html.erb
<div class='mt-2'>
  <% if controller_name != 'user_sessions' %>
    <%= link_to t('devise.actions.login'), login_path %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'user_passwords' %>
    <%= link_to t('devise.passwords.new.forgot_your_password'), recover_password_path %><br />
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'user_confirmations' %>
    <%= link_to t('devise.confirmations.new.did_not_receive_confirmation_instructions'), confirmation_path %><br />
  <% end %>
</div>

engines/landing/app/views/landing/shared/_footer.html.erb
<div class='container'>
  <hr class='divider-line'>
</div>

<footer>
  <div class='container main-footer'>
    <div class='row'>
      <div class='col-md-4'>
        <h5><%= t('shared.site_name') %></h5>
        <address>
          Islamisches Zentrum Al-Nour<br />
          Sievekingsallee 191<br />
          22111, Hamburg<br />
          Germany
        </address>

        <address>
          <i class='fa fa-envelope'></i>
          <i>masajid.world(@)gmail.com</i>
        </address>
      </div>

      <div class='col-md-4'>
        <h5><%= t('landing.footer.useful_links') %></h5>
        <ul class='list-unstyled'>
          <li><%= link_to t('landing.footer.home'), root_path %></li>
          <li><%= link_to t('shared.volunteers.new.header'), new_volunteer_path %></li>
          <li><%= link_to t('landing.footer.terms'), root_path %></li>
          <li><%= link_to t('landing.footer.privacy'), root_path %></li>
        </ul>
      </div>
      <div class='col-md-4'>
        <h5><%= t('landing.footer.follow_us') %></h5>
        <ul class='list-unstyled'>
          <li><a href='#'>Facebook</a></li>
          <li><a href='#'>Twitter</a></li>
          <li><a href='#'>Youtube</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class='copyright-footer'>
    <p>
      <%= t('landing.footer.copyright_html', year: Date.current.year) %>
    </p>

    <p>
      <a href='#'><%= t('shared.footer.back_to_top') %></a>
    </p>
  </footer>
</footer>

engines/landing/app/views/landing/shared/_google_analytics.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= google_analytics_tracking_id %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<%= google_analytics_tracking_id %>');
</script>

engines/landing/app/views/landing/shared/_header.html.erb
<nav class='navbar navbar-expand-md navbar-dark fixed-top bg-dark'>
  <div class='container'>
    <%= link_to t('shared.site_name'), root_path, class: 'navbar-brand' %>
    <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#landingNavbar' aria-controls='landingNavbar' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='landingNavbar'>
      <ul class='navbar-nav mr-auto'>
        <li class='nav-item'>
          <%= link_to t('shared.volunteers.new.header'), new_volunteer_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class='navbar-nav ml-auto'>
        <li class='nav-item dropdown'>
          <%= link_to '#', class: 'nav-link dropdown-toggle', id: 'localeDropdown', data: { toggle: 'dropdown'} , aria: { haspopup: 'true', expanded: 'false' } do %>
            <%= locale_with_icon(I18n.locale) %>
          <% end %>
          <div class='dropdown-menu' aria-labelledby='localeDropdown'>
            <% alternate_locales.each do |locale| %>
              <%= link_to url_for(locale: locale), class: 'dropdown-item' do %>
                <%= locale_with_icon(locale) %>
              <% end %>
            <% end %>
          </div>
        </li>

        <% if user_signed_in? %>
          <li class='nav-item'>
            <%= link_to t('landing.admin_panel'), '/admin', class: 'nav-link' %>
          </li>

          <li class='nav-item'>
            <%= link_to t('devise.actions.logout'), logout_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class='nav-item'>
            <%= link_to t('devise.actions.login'), login_path, class: 'nav-link' %>
          </li>

          <li class='nav-item'>
            <%= link_to t('landing.create_account'), new_account_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

engines/landing/app/views/landing/user_sessions/_form.html.erb
<%= form_for(resource, as: resource_name, url: create_new_session_path) do |f| %>
  <div class='form-label-group'>
    <%= f.email_field(
      :email,
      autofocus: true,
      required: true,
      autocomplete: 'email',
      placeholder: Content::User.human_attribute_name(:email),
      class: 'form-control'
    ) %>
    <%= f.label :email, Content::User.human_attribute_name(:email) %>
  </div>

  <div class='form-label-group'>
    <%= f.password_field(
      :password,
      autocomplete: 'current-password',
      placeholder: Content::User.human_attribute_name(:password),
      class: 'form-control'
    ) %>
    <%= f.label :password, Content::User.human_attribute_name(:password) %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class='checkbox'>
      <%= f.label :remember_me do %>
        <%= f.check_box :remember_me %> <%= t('devise.sessions.new.remember_me') %>
      <% end %>
    </div>
  <% end %>

  <%= f.submit t('devise.actions.login'), class: 'btn btn-block' %>

  <%= render 'landing/shared/devise_links' %>
<% end %>

engines/landing/app/views/landing/user_sessions/new.html.erb
<div class='row devise'>
  <div class='col-md-6 image'>
    <%= image_tag 'landing/devise.png', alt: t('landing.user_sessions.new.title'), class: 'img-fluid' %>
  </div>

  <div class='col-md-6'>
    <h1 class='form-header'>
      <%= t('devise.actions.login') %>
    </h1>

    <%= render 'form' %>
  </div>
</div>