engines/admin/config/routes.rb
Admin::Engine.routes.draw do
  root 'dashboards#index'

  resources :accounts, except: %i[show new create] do
    member do
      put :accept
      put :decline
    end
  end
  resources :cities, except: :show
  resources :regions, except: :show
  resources :countries, except: :show
  resources :pages, except: :show do
    post :sort, on: :collection
  end
  resources :articles, except: :show
  resources :messages, only: %i[index show]
  resources :volunteers, only: :index
  resources :subscribers, only: :index
  resources :newsletters, except: :show
  resources :sidebar_contents, except: :show, path: :sidebar
  resource :slider, only: %i[edit update]
  resource :social_network, only: %i[edit update]
  resource :configuration, only: %i[edit update]
  resource :language, only: %i[edit update]
  resource :about, only: %i[edit update], controller: :about
  resource :user, only: %i[edit update]
  resource :domain, only: %i[edit update]

  get '/:resource/:resource_id/translations' => 'translations#index', as: :translations

  namespace :api do
    resources :regions, only: :index
    resources :cities, only: :index
  end

  match '*path' => 'errors#not_found', via: :all
end

engines/admin/app/controllers/admin/translations_controller.rb
require_dependency 'admin/application_controller'

module Admin
  class TranslationsController < ApplicationController
    RESOURCE_NAME_MAPPING = {
      'sidebar' => 'sidebar_content'
    }.freeze

    def index
      render(resource_name)
    end

    private

    def resource_name
      @resource_name ||= RESOURCE_NAME_MAPPING[params[:resource]] || params[:resource].singularize
    end

    def klass
      @klass ||= "Content::#{resource_name.classify}".constantize
    end

    def resource
      @resource ||= klass.find(params[:resource_id])
    end
    helper_method :resource

    def wrapper_center?
      true
    end
    helper_method :wrapper_center?
  end
end

engines/admin/app/helpers/admin/translations_helper.rb
module Admin
  module TranslationsHelper
    def locales_for_translations
      @locales_for_translations ||= current_account.supported_locales.reject(&:blank?)
    end
  end
end

engines/admin/app/views/admin/translations/_seo_content.html.erb
<%= seo_content_form.globalize_fields_for locale do |g| %>
  <%= form_group_for g, :meta_title, label: Content::SeoContent.human_attribute_name(:meta_title) do %>
    <%= g.input :meta_title, label: false, hint: t('simple_form.hints.content/page.meta_title_html') %>
  <% end %>

  <%= form_group_for g, :meta_description, label: Content::SeoContent.human_attribute_name(:meta_description) do %>
    <%= g.input :meta_description, as: :text, label: false, hint: t('simple_form.hints.content/page.meta_description') %>
  <% end %>
<% end %>

engines/admin/app/views/admin/translations/_settings.html.erb
<ul class='nav nav-tabs' id='localeTab' role='tablist'>
  <% locales_for_translations.each do |locale| %>
    <li class='nav-item'>
      <a
        class='nav-link <%= 'active' if current_account.admin_locale == locale %>'
        id='<%= locale %>-tab'
        data-toggle='tab'
        href='#<%= locale %>'
        role='tab'
        aria-controls='<%= locale %>' aria-selected='true'
      >
        <%= t("shared.locales.#{locale}") %>
      </a>
    </li>
  <% end %>
</ul>

engines/admin/app/views/admin/translations/article.html.erb
<% content_for :page_title do %>
  <%= t('admin.translations.article.header') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to edit_article_path(resource), class: 'btn btn-success' do %>
    <i class='fa fa-edit'></i>
    <%= t('shared.actions.edit') %>
  <% end %>
  <%= link_to t('shared.actions.new'), new_article_path, class: 'btn btn-info' %>
  <%= link_to t('shared.actions.back_to_list'), articles_path, class: 'btn btn-secondary' %>
<% end %>

<%= render 'settings' %>

<%= simple_form_for resource do |f| %>
  <%= f.simple_fields_for :seo_content, (f.object.seo_content || f.object.build_seo_content) do |seo_content_form| %>
    <div class='tab-content' id='localeTabContent'>
      <% locales_for_translations.each_with_index do |locale, index| %>
        <div
          class='tab-pane fade <%= 'show active' if current_account.admin_locale == locale %>'
          id='<%= locale %>'
          role='tabpanel'
          aria-labelledby='<%= locale %>-tab'
        >
          <% I18n.with_locale(locale) do %>
            <%= f.globalize_fields_for locale do |g| %>
              <%= form_group_for g, :title, label: Content::Article.human_attribute_name(:title) do %>
                <%= g.input :title, label: false %>
              <% end %>

              <%= form_group_for g, :slug, label: Content::Article.human_attribute_name(:slug) do %>
                <%= g.input :slug, label: false %>
              <% end %>

              <%= form_group_for g, :summary, label: Content::Article.human_attribute_name(:summary) do %>
                <%= g.input :summary, as: :text, label: false, input_html: { rows: 5 } %>
              <% end %>

              <%= form_group_for g, :body, label: Content::Article.human_attribute_name(:body) do %>
                <%= g.input :body, as: :trix_editor, input_html: { dir: dir }, label: false %>
              <% end %>

              <hr>

              <%= render 'seo_content', seo_content_form: seo_content_form, locale: locale %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= f.button :submit, class: 'btn btn-info pull-right' %>
  <% end %>
<% end %>

engines/admin/app/views/admin/translations/configuration.html.erb
<% content_for :page_title do %>
  <%= t('admin.translations.configuration.header') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to edit_configuration_path, class: 'btn btn-success' do %>
    <i class='fa fa-edit'></i>
    <%= t('shared.actions.edit') %>
  <% end %>
<% end %>

<%= render 'settings' %>

<%= simple_form_for current_account, url: configuration_path do |f| %>
  <%= f.simple_fields_for :seo_content, (f.object.seo_content || f.object.build_seo_content) do |seo_content_form| %>
    <div class='tab-content' id='localeTabContent'>
      <% locales_for_translations.each_with_index do |locale, index| %>
        <div
          class='tab-pane fade <%= 'show active' if current_account.admin_locale == locale %>'
          id='<%= locale %>'
          role='tabpanel'
          aria-labelledby='<%= locale %>-tab'
        >
          <% I18n.with_locale(locale) do %>
            <%= f.globalize_fields_for locale do |g| %>
              <%= form_group_for g, :mosque, label: Content::Account.human_attribute_name(:mosque) do %>
                <%= g.input :mosque, label: false %>
              <% end %>

              <hr>

              <%= render 'seo_content', seo_content_form: seo_content_form, locale: locale %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= f.button :submit, class: 'btn btn-info pull-right' %>
  <% end %>
<% end %>

engines/admin/app/views/admin/translations/page.html.erb
<% content_for :page_title do %>
  <%= t('admin.translations.page.header') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to edit_page_path(resource), class: 'btn btn-success' do %>
    <i class='fa fa-edit'></i>
    <%= t('shared.actions.edit') %>
  <% end %>
  <%= link_to t('shared.actions.new'), new_page_path, class: 'btn btn-info' %>
  <%= link_to t('shared.actions.back_to_list'), pages_path, class: 'btn btn-secondary' %>
<% end %>

<%= render 'settings' %>

<%= simple_form_for resource do |f| %>
  <%= f.simple_fields_for :seo_content, (f.object.seo_content || f.object.build_seo_content) do |seo_content_form| %>
    <div class='tab-content' id='localeTabContent'>
      <% locales_for_translations.each_with_index do |locale, index| %>
        <div
          class='tab-pane fade <%= 'show active' if current_account.admin_locale == locale %>'
          id='<%= locale %>'
          role='tabpanel'
          aria-labelledby='<%= locale %>-tab'
        >
          <% I18n.with_locale(locale) do %>
            <%= f.globalize_fields_for locale do |g| %>
              <%= form_group_for g, :name, label: Content::Page.human_attribute_name(:name) do %>
                <%= g.input :name, label: false %>
              <% end %>

              <%= form_group_for g, :description, label: Content::Page.human_attribute_name(:description) do %>
                <%= g.input :description, as: :text, label: false %>
              <% end %>

              <%= form_group_for g, :permalink, label: Content::Page.human_attribute_name(:permalink) do %>
                <%= g.input :permalink, label: false %>
              <% end %>

              <hr>

              <%= render 'seo_content', seo_content_form: seo_content_form, locale: locale %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= f.button :submit, class: 'btn btn-info pull-right' %>
  <% end %>
<% end %>

engines/admin/app/views/admin/translations/sidebar_content.html.erb
<% content_for :page_title do %>
  <%= t('admin.translations.sidebar_content.header') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to edit_sidebar_content_path(resource), class: 'btn btn-success' do %>
    <i class='fa fa-edit'></i>
    <%= t('shared.actions.edit') %>
  <% end %>
  <%= link_to t('shared.actions.new'), new_sidebar_content_path, class: 'btn btn-info' %>
  <%= link_to t('shared.actions.back_to_list'), sidebar_contents_path, class: 'btn btn-secondary' %>
<% end %>

<%= render 'settings' %>

<%= simple_form_for resource do |f| %>
  <div class='tab-content' id='localeTabContent'>
    <% locales_for_translations.each_with_index do |locale, index| %>
      <div
        class='tab-pane fade <%= 'show active' if current_account.admin_locale == locale %>'
        id='<%= locale %>'
        role='tabpanel'
        aria-labelledby='<%= locale %>-tab'
      >
        <% I18n.with_locale(locale) do %>
          <%= f.globalize_fields_for locale do |g| %>
            <%= form_group_for g, :title, label: Content::SidebarContent.human_attribute_name(:title) do %>
              <%= g.input :title, label: false %>
            <% end %>

            <%= form_group_for g, :body, label: Content::SidebarContent.human_attribute_name(:body) do %>
              <%= g.input :body, as: :text, label: false, input_html: { rows: 5 } %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= f.button :submit, class: 'btn btn-info pull-right' %>
<% end %>

engines/admin/app/views/admin/translations/slider.html.erb
<% content_for :page_title do %>
  <%= t('admin.translations.slider.header') %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to edit_slider_path, class: 'btn btn-success' do %>
    <i class='fa fa-edit'></i>
    <%= t('shared.actions.edit') %>
  <% end %>
<% end %>

<%= render 'settings' %>

<%= simple_form_for (current_account.slider || current_account.build_slider), url: slider_path do |f| %>
  <div class='tab-content' id='localeTabContent'>
    <% locales_for_translations.each_with_index do |locale, index| %>
      <div
        class='tab-pane fade <%= 'show active' if current_account.admin_locale == locale %>'
        id='<%= locale %>'
        role='tabpanel'
        aria-labelledby='<%= locale %>-tab'
      >
        <% I18n.with_locale(locale) do %>
          <%= f.globalize_fields_for locale do |g| %>
            <%= form_group_for g, :title, label: Content::Slider.human_attribute_name(:title) do %>
              <%= g.input :title, label: false %>
            <% end %>

            <%= form_group_for g, :body, label: Content::Slider.human_attribute_name(:body) do %>
              <%= g.input :body, as: :text, label: false %>
            <% end %>

            <%= form_group_for g, :link_text, label: Content::Slider.human_attribute_name(:link_text) do %>
              <%= g.input :link_text, label: false %>
            <% end %>

            <%= form_group_for g, :link, label: Content::Slider.human_attribute_name(:link) do %>
              <%= g.input :link, label: false %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= f.button :submit, class: 'btn btn-info pull-right' %>
<% end %>